name: airflow-dag-validation
author: jayamanikharyono
desription: Run Airflow DAG Validation on Airflow Project
branding:
  icon: check
  color: cyan

inputs:
  dagPaths:
    description: DAG dir to validate
    required: false
    default: "dags"
  requirementsFile:
    description: path to requirements file that airflow use to run the DAG files.
    required: false
    default: "requirements.txt"
  varFile:
    description: path to var.json file that will be used to set Variable on airflow
    required: false
    default: ""

outputs:
  validator-result:
    description: dag validator result
    value: ${{ steps.run }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirementsFile }}
    - ${{ inputs.dagPaths }}
    - ${{ inputs.varFile }}
